name: Nexus CLI (2 nodes, persist state)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"   # chạy mỗi 5 giờ để kịp backup trước mốc 6h

permissions:
  contents: read
  actions: read

env:
  # DÁN 2 ID của bạn, cách nhau bởi dấu cách (ví dụ: "36001861 35907001")
  NODE_IDS: "36052788 36063227"

jobs:
  nexus:
    runs-on: ubuntu-latest
    timeout-minutes: 355

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- FIX 1: tìm artifact run trước theo đúng workflow hiện tại ---
      - name: Download previous state artifact
        uses: dawidd6/action-download-artifact@v6
        continue-on-error: true                # không fail lần chạy đầu
        with:
          # Dùng đúng tên workflow hiện tại thay vì "main.yml"
          workflow: ${{ github.workflow }}
          name: nexus-state
          path: /tmp/nexus-state
          if_no_artifact_found: ignore
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore state (if present)
        shell: bash
        run: |
          set -euxo pipefail
          sudo mkdir -p /opt/state
          sudo chown -R "$USER:$USER" /opt/state
          # Khôi phục ~/.nexus nếu có
          if [ -f /tmp/nexus-state/home-runner-nexus.tar.gz ]; then
            tar -xzf /tmp/nexus-state/home-runner-nexus.tar.gz -C "$HOME"
          fi
          # Khôi phục /opt/state nếu có
          if [ -f /tmp/nexus-state/opt-state.tar.gz ]; then
            sudo tar -xzf /tmp/nexus-state/opt-state.tar.gz -C /
            sudo chown -R "$USER:$USER" /opt/state
          fi
          mkdir -p /opt/state/logs

      - name: Prepare system
        shell: bash
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y tmux curl util-linux psmisc

      - name: Install Nexus CLI
        shell: bash
        run: |
          set -euxo pipefail
          curl -sSf https://cli.nexus.xyz/ -o install.sh
          chmod +x install.sh
          NONINTERACTIVE=1 ./install.sh
          echo "$HOME/.nexus/bin" >> "$GITHUB_PATH"
          nexus-cli --version || true

      - name: Ensure start script exists
        shell: bash
        run: |
          set -euxo pipefail
          install -d -m 755 /opt/state /opt/state/logs
          cat <<'SCRIPT' > /opt/state/start-nexus.sh
          #!/usr/bin/env bash
          set -euo pipefail
          NODE_ID="$1"
          LOG_DIR="/opt/state/logs"
          mkdir -p "$LOG_DIR"
          export PATH="$HOME/.nexus/bin:$PATH"
          while true; do
            echo "[$(date -Is)] starting node ${NODE_ID}"
            nexus-cli start --headless --node-id "${NODE_ID}" 2>&1 | tee -a "${LOG_DIR}/node${NODE_ID}.log"
            echo "[$(date -Is)] node ${NODE_ID} exited, restart in 15s..."
            sleep 15
          done
          SCRIPT
          chmod +x /opt/state/start-nexus.sh
          head -n 12 /opt/state/start-nexus.sh

      - name: Start 2 Nexus nodes in tmux
        shell: bash
        run: |
          set -euxo pipefail
          for ID in $NODE_IDS; do
            tmux has-session -t "node${ID}" 2>/dev/null && tmux kill-session -t "node${ID}" || true
          done
          for ID in $NODE_IDS; do
            tmux new-session -d -s "node${ID}" "/opt/state/start-nexus.sh ${ID}"
          done
          tmux ls || true

      # Mở SSH (tmate) khi chạy tay
      - name: Open tmate (manual only)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: mxschmitt/action-tmate@v3
        with:
          # để true nếu bạn đã add SSH key vào GitHub profile; false nếu muốn ai có log cũng vào được (chỉ nên dùng repo private)
          limit-access-to-actor: false

      - name: Let it run ~5h50
        shell: bash
        run: |
          sleep $((5*60*60 + 50*60))

      # --- FIX 2: tar bỏ qua nếu chưa có thư mục, và upload ignore khi rỗng ---
      - name: Create state archives
        if: always()
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p /tmp/state-bundle
          mkdir -p "$HOME/.nexus" /opt/state || true
          tar -czf /tmp/state-bundle/home-runner-nexus.tar.gz -C "$HOME" .nexus 2>/dev/null || true
          sudo tar -czf /tmp/state-bundle/opt-state.tar.gz -C / opt/state 2>/dev/null || true
          sudo chown "$USER:$USER" /tmp/state-bundle/*.tar.gz || true

      - name: Upload state artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nexus-state
          path: /tmp/state-bundle
          if-no-files-found: ignore
          retention-days: 14
