name: Nexus CLI (4 nodes, persist state)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"   # chạy mỗi 5 giờ để kịp backup trước mốc 6h

permissions:
  contents: read
  actions: read

# KHÓA theo TỪNG FILE WORKFLOW (mỗi *.yml chỉ 1 run tại 1 thời điểm)
concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: false

env:
  NODE_IDS: "36908693 36435407 36387224 36570727"
  LOG_MAX_MB: "50"              # giới hạn log mỗi node trong snapshot (MB)
  IDLE_MAX_MIN: "15"            # watchdog: nếu log đứng > X phút thì restart
  RUN_HOURS: "5"                # tổng thời gian chạy ~ 5h50' để kịp snapshot
  RUN_EXTRA_MIN: "50"
  START_STAGGER_BASE: "5"       # giãn khởi động giữa các node
  START_STAGGER_JITTER: "10"
  START_STAGGER_STEP: "2"
  TMUX_SOCKET: "nexus"
  ARTIFACT_NAME: "nexus-state"

defaults:
  run:
    shell: bash

jobs:
  nexus:
    runs-on: ubuntu-latest
    timeout-minutes: 355

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Khôi phục state (best-effort nếu chưa có artifact)
      - name: Download previous state artifact (best-effort)
        uses: dawidd6/action-download-artifact@v6
        continue-on-error: true
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: /tmp/nexus-state
          if_no_artifact_found: ignore
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore state (if present)
        run: |
          set -Eeuo pipefail
          sudo mkdir -p /opt/state
          sudo chown -R "$USER:$USER" /opt/state

          # Khôi phục ~/.nexus (nếu có)
          if [ -f /tmp/nexus-state/home-runner-nexus.tar.gz ]; then
            tar -xzf /tmp/nexus-state/home-runner-nexus.tar.gz -C "$HOME"
          fi

          # Khôi phục /opt/state (nếu có)
          if [ -f /tmp/nexus-state/opt-state.tar.gz ]; then
            sudo tar -xzf /tmp/nexus-state/opt-state.tar.gz -C /
            sudo chown -R "$USER:$USER" /opt/state
          fi

          mkdir -p /opt/state/logs

      - name: Prepare system
        run: |
          set -Eeuo pipefail
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y -q tmux curl rsync coreutils

      # 2) Cài Nexus CLI (robust: retry + HTML guard)
      - name: Install Nexus CLI (robust)
        run: |
          set -Eeuo pipefail
          # Tải script về file (retry tăng dần)
          for i in {1..5}; do
            curl -4 -fsSL -A "curl/8.x github-actions" https://cli.nexus.xyz -o /tmp/nexus-install.sh && break || sleep $((5*i))
          done

          echo "== First lines of installer =="
          head -n 5 /tmp/nexus-install.sh || true

          # Guard: nếu trả về HTML/redirect thì fail sớm
          if grep -qiE '<(html|head|title|script)' /tmp/nexus-install.sh; then
            echo "Installer returned HTML (có thể bị redirect/protection)."
            exit 1
          fi

          chmod +x /tmp/nexus-install.sh
          bash /tmp/nexus-install.sh

          # Thêm path binary do installer đặt trong ~/.nexus/bin
          echo "$HOME/.nexus/bin" >> "$GITHUB_PATH"

      # 3) Script chạy node (shebang ở cột 1, có watchdog + trap)
      - name: Ensure start script exists
        run: |
          set -Eeuo pipefail
          install -d -m 755 /opt/state /opt/state/logs

          cat <<'SCRIPT' > /opt/state/start-nexus.sh
#!/usr/bin/env bash
set -Eeuo pipefail

NODE_ID="$1"
LOG_DIR="/opt/state/logs"
LOG_FILE="${LOG_DIR}/node${NODE_ID}.log"

mkdir -p "$LOG_DIR"

# Binaries từ CLI
export PATH="$HOME/.nexus/bin:$PATH"

# Cleanup khi runner dừng
_cleanup() {
  echo "[$(date -Is)] cleanup for node ${NODE_ID}"
  # best-effort: kill child nexus nếu còn
  pkill -f "nexus-network start --node-id ${NODE_ID}" || true
}
trap _cleanup INT TERM EXIT

# In version (không fail nếu vắng)
command -v nexus-network && nexus-network --version || true

IDLE_MAX_MIN="${IDLE_MAX_MIN:-15}"

while true; do
  echo "[$(date -Is)] starting node ${NODE_ID}"

  ( stdbuf -oL -eL nexus-network start --node-id "${NODE_ID}" 2>&1 | tee -a "${LOG_FILE}" ) &
  NPID=$!

  while kill -0 "$NPID" 2>/dev/null; do
    sleep 60
    if [ -f "${LOG_FILE}" ]; then
      LAST=$(stat -c %Y "${LOG_FILE}" 2>/dev/null || echo 0)
      NOW=$(date +%s)
      if [ $((NOW - LAST)) -gt $((IDLE_MAX_MIN*60)) ]; then
        echo "[$(date -Is)] no log > ${IDLE_MAX_MIN}m → restart ${NODE_ID}"
        kill -TERM "$NPID" 2>/dev/null || true
        sleep 5
        kill -KILL "$NPID" 2>/dev/null || true
        break
      fi
    fi
  done

  echo "[$(date -Is)] node ${NODE_ID} exited, restart in 15s..."
  sleep 15
done
SCRIPT

          chmod +x /opt/state/start-nexus.sh
          head -n 20 /opt/state/start-nexus.sh

      # 4) Khởi chạy 4 node trong tmux socket riêng (stagger + nice/ionice)
      - name: Start Nexus nodes in tmux (stagger + nice/ionice)
        run: |
          set -Eeuo pipefail

          # Dọn session cũ theo từng node (nếu còn)
          for ID in $NODE_IDS; do
            tmux -L "$TMUX_SOCKET" has-session -t "node${ID}" 2>/dev/null && \
              tmux -L "$TMUX_SOCKET" kill-session -t "node${ID}" || true
          done

          i=0
          for ID in $NODE_IDS; do
            JITTER=$(( RANDOM % START_STAGGER_JITTER + 1 ))
            SLEEP=$(( START_STAGGER_BASE + JITTER + i*START_STAGGER_STEP ))
            echo "Stagger start node ${ID} sau ${SLEEP}s"
            sleep "${SLEEP}"

            tmux -L "$TMUX_SOCKET" new-session -d -s "node${ID}" \
              "ulimit -n 65535; nice -n 5 ionice -c2 -n5 /opt/state/start-nexus.sh ${ID}"

            i=$((i+1))
          done

          tmux -L "$TMUX_SOCKET" ls || true

      # 5) SSH debug (thủ công; hoặc bật bởi repo variable ENABLE_TMATE=1)
      - name: Open tmate (debug)
        if: ${{ github.event_name == 'workflow_dispatch' || vars.ENABLE_TMATE == '1' }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false

      # 6) Chạy ~5h50' rồi snapshot + upload
      - name: Let it run
        run: |
          set -Eeuo pipefail
          S=$(( RUN_HOURS*3600 + RUN_EXTRA_MIN*60 ))
          echo "Sleeping for ${S}s (~$((S/3600))h$(((S%3600)/60))m)"
          sleep "${S}"

      # 7) Nếu lỗi, tail nhanh log để dễ chẩn đoán
      - name: Quick tail logs on failure
        if: failure()
        run: |
          set -Eeuo pipefail
          echo "== Tail 200 lines mỗi log =="
          for f in /opt/state/logs/node*.log; do
            [ -f "$f" ] && { echo "--- $f ---"; tail -n 200 "$f" || true; }
          done

      # 8) Snapshot ổn định + giới hạn log + nén
      - name: Create state archives
        if: always()
        run: |
          set -Eeuo pipefail
          mkdir -p /tmp/state-bundle

          # ~/.nexus (nếu có)
          if [ -d "$HOME/.nexus" ]; then
            tar -czf /tmp/state-bundle/home-runner-nexus.tar.gz -C "$HOME" .nexus
          fi

          # /opt/state → snapshot bằng rsync (clone sang /tmp trước khi nén)
          if [ -d /opt/state ]; then
            SNAP=/tmp/snap/opt/state
            mkdir -p "$SNAP"
            rsync -a --delete /opt/state/ "$SNAP/"

            # cắt log về LOG_MAX_MB
            MAX_MB=${LOG_MAX_MB:-50}
            MAX_BYTES=$((MAX_MB*1024*1024))
            if [ -d "$SNAP/logs" ]; then
              find "$SNAP/logs" -type f -name 'node*.log' 2>/dev/null | while read -r f; do
                SZ=$(stat -c%s "$f" 2>/dev/null || echo 0)
                if [ "$SZ" -gt "$MAX_BYTES" ]; then
                  tail -c "$MAX_BYTES" "$f" > "$f.tmp" && mv "$f.tmp" "$f"
                fi
              done
            fi

            sudo tar -czf /tmp/state-bundle/opt-state.tar.gz -C /tmp/snap opt/state
            sudo chown "$USER:$USER" /tmp/state-bundle/opt-state.tar.gz
          fi

          echo "== Bundle contents =="
          ls -lah /tmp/state-bundle || true

      - name: Upload state artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: /tmp/state-bundle
          retention-days: 14
